AddTimes =
    let
        ParsedTime =
            Table.AddColumn(
                ExpandFechas,
                "StartTimeParsed",
                (r) =>
                    let
                        rawStart   = r[StartTime],
                        rawText    = if rawStart = null then null else Text.Trim(Text.From(rawStart)),
                        tryTime    = try Time.From(rawStart),
                        tryText    = if tryTime[HasError] then try Time.FromText(rawText, "en-US") else try tryTime,
                        parsed     = if not tryTime[HasError] then tryTime[Value]
                                     else if not tryText[HasError] then tryText[Value]
                                     else null
                    in
                        parsed,
                type time
            ),

        WithDateTimes =
            Table.AddColumn(
                ParsedTime,
                "InicioLocal",
                (r) =>
                    if r[StartTimeParsed] = null then null
                    else
                        #datetime(
                            Date.Year(r[Fechas]),
                            Date.Month(r[Fechas]),
                            Date.Day(r[Fechas]),
                            Time.Hour(r[StartTimeParsed]),
                            Time.Minute(r[StartTimeParsed]),
                            0
                        ),
                type datetime
            ),

        WithEnd =
            Table.AddColumn(
                WithDateTimes,
                "FinLocal",
                each if [InicioLocal] = null
                     then null
                     else [InicioLocal] + #duration(0, 0, Number.From([DurationMin]), 0),
                type datetime
            )
    in
        WithEnd
